/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//This program consists of 2 two program one is I2C Clock and MCO1 Pin where we can see HSE CLOCK FREQUENCY
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDR 0x40023800UL
#define RCC_APB1ENR_OFFSET 0x40
#define RCC_APB1ENR_ADDR 0x40023840UL

#define RCC_CR_ADDR 0x40023800UL

#define RCC_AHB1ENR_OFFSET 0x30
#define RCC_AHB1ENR_ADDR 0x40023830UL

#define GPIOA_BASE_ADDR 0x40020000UL
#define GPIOA_MODE_ADDR 0x40020000UL

#define RCC_CFGR_OFFSET 0x08
#define RCC_CFGR_ADDR 0x40023808UL

#define I2C1_BASE_ADDR  0x40005400UL
#define I2C1_CR2_OFFSET 0x04
#define I2C1_CR2_ADDR 0x40005404UL

int main(void)
{
	uint32_t *pApb1enrAddr = (uint32_t*)RCC_APB1ENR_ADDR;
	uint32_t *pI2c1Cr2Addr = (uint32_t*)I2C1_CR2_ADDR;
	uint32_t *pRccCrAddr = (uint32_t*)RCC_CR_ADDR;
	uint32_t *pGpioaModeAddr = (uint32_t*)GPIOA_MODE_ADDR;
	uint32_t *pRccCfgrAddr = (uint32_t*)RCC_CFGR_ADDR;
	uint32_t *pRccAhb1enrAddr =(uint32_t*)RCC_AHB1ENR_ADDR;
	//Enabled APB1 CLOCK
	*pApb1enrAddr |= (1<<21);
	//Enable 2MHZ FREQUENCY FOR I2C
	*pI2c1Cr2Addr |= (0b000010<<0);
	//GPIOA CLOCK
	*pRccAhb1enrAddr |= 1;
	//Enable HSE On
	*pRccCrAddr |= (1<<16);
	//Set alternate function in portA pin no 8
	*pGpioaModeAddr |= (0b10 << 16);
	// By default the Alternate Function is MCO

	// Route HSE Oscillator to MCO
	*pRccCfgrAddr |= (0b10 << 21);
   while(1){

}
}
