/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_AHB1ENR_OFFSET 0x30UL
#define RCC_AHB1ENR_ADDR 0x40023830UL

#define GPIOC_BASE_ADDR 0x40020800UL
#define GPIOC_MODE_ADDR 0x40020800UL
#define GPIOC_PUPDR_ADDR 0x4002080CUL
#define GPIOC_ODR_ADDR 0x40020814UL

int main(void)
{
    /* Loop forever */
	uint32_t *pAhb1EnrAddr = (uint32_t*)RCC_AHB1ENR_ADDR;
	uint32_t *pGpiocModeAddr = (uint32_t*)GPIOC_MODE_ADDR;
	uint32_t *pGpiocPupdrAddr = (uint32_t*)GPIOC_PUPDR_ADDR;
	uint32_t *pGpiocOdrAddr = (uint32_t*)GPIOC_ODR_ADDR;
	//Enable clock for GPIOC
	*pAhb1EnrAddr |= (1<<2);
	//Configure PC1 as Output
	*pGpiocModeAddr |= (0b01<<2);
	//configure PC1 as Pull Down
	*pGpiocPupdrAddr |= (0b10 << 2);

	for(;;){
		//Enable Led to glow
		*pGpiocOdrAddr |= (1<<1);
		for(uint32_t i=0; i<1777777; i++);
		*pGpiocOdrAddr &= ~(1<<1);
		for(uint32_t i=0; i<1777777; i++);
	}
}
