/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
// Configuring RCC Macros
#define RCC_BASE_ADDR 0x40023800UL
#define RCC_APB1ENR_OFFSET 0x40UL
#define RCC_APB1ENR_ADDR 0x40023840UL

#define RCC_CFGR_OFFSET 0x08UL
#define RCC_CFGR_ADDR 0x40023808UL

#define RCC_CR_ADDR RCC_BASE_ADDR

#define RCC_AHB1ENR_OFFSET 0x30UL
#define RCC_AHB1ENR_ADDR 0x40023830UL
//Configuring GPIO Macros
#define GPIOA_BASE_ADDR	0x40020000UL
#define GPIOB_BASE_ADDR	0x40020400UL
#define GPIOC_BASE_ADDR	0x40020800UL
#define GPIOD_BASE_ADDR	0x40020C00UL
#define GPIOE_BASE_ADDR	0x40021000UL

#define GPIOx_MODER_OFFSET 0x00UL
#define GPIOx_OTYPER_OFFSET 0x04UL
#define GPIOx_OSPEEDR_OFFSET 0x08UL
#define GPIOx_PUPDR_OFFSET 0x0CUL
#define GPIOx_IDR_OFFSET 0x10UL
#define GPIOx_ODR_OFFSET 0x14UL
#define GPIOx_BSRR_OFFSET 0x18UL
#define GPIOx_LCKR_OFFSET 0x1CUL
#define GPIOx_AFRL_OFFSET 0x20UL
#define GPIOx_AFRH_OFFSET 0x24UL

#define GPIOD_MODE_ADDR 0x40020C00UL
#define GPIOD_OTYPER_ADDR 0x40020C04UL
#define GPIOD_OSPEEDR_ADDR 0x40020C08UL
#define GPIOD_PUPDR_ADDR 0x40020C0CUL
#define GPIOD_IDR_ADDR 0x40020C10UL
#define GPIOD_ODR_ADDR 0x40020C14UL
#define GPIOD_BSRR_ADDR 0x40020C18UL
#define GPIOD_LCKR_ADDR 0x40020C1CUL
#define GPIOD_AFRL_ADDR 0x40020C20UL
#define GPIOD_AFRH_ADDR 0x40020C24UL

#define GPIOA_IDR_ADDR 0x40020010

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif*/
int main(void)
{	//Assigning pointers to Address
	uint32_t *pGpiodModerAddr = (uint32_t*)GPIOD_MODE_ADDR;
	uint32_t *pGpiodPupdrAddr = (uint32_t*)GPIOD_PUPDR_ADDR;
	uint32_t *pGpiodOdrAddr = (uint32_t*)GPIOD_ODR_ADDR;
	uint32_t *Ahb1EnrAddr = (uint32_t*)RCC_AHB1ENR_ADDR;
	uint32_t *pGpioIdrAddr = (uint32_t*)GPIOA_IDR_ADDR;

	//Enable PortD clock
	*Ahb1EnrAddr |= ((1 << 3) | (1<<0));

	// Configure PD12, PD13, PD14, PD15 as output
	*pGpiodModerAddr |= (0x55 << 24);
	// Activate Pull down resistor at default
	*pGpiodPupdrAddr |= (0xAA << 24);

	//loop for continous execution
	for(;;){
		//Enable all leds to glow
		if(*pGpioIdrAddr & 1){
		*pGpiodOdrAddr |= (0xF << 12);
		}
		//Turn off all leds
		else{
		*pGpiodOdrAddr &= ~(0xF << 12);

		}
	}
}


