/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(long time){
	RCC->APB1ENR &= ~(1 << 0);
	RCC->APB1ENR |= (1 << 0); // To enable clock for Timer 2
	TIM2->CR1 &= ~(1 << 0); //To disable counter
	TIM2->PSC = 4200-1;//To set prescalar value
	TIM2->ARR = 2000; // Loading ARR Value
	TIM2->CR1 |= (1 << 0); // Start the counter
	TIM2->CNT = 0;
	while(TIM2->CNT < time);

}

int main(void)
{
    /* Loop forever */

	RCC->CR |= (1 << 0);
	RCC->AHB1ENR &= ~(1<<3);
	RCC->AHB1ENR |= (1<<3);
	GPIOD->MODER &= ~(0b01 << 24);
	GPIOD->MODER |= (0b01 << 24);
	GPIOD->PUPDR &= ~(0b10 << 24);
	GPIOD->PUPDR |= (0b10 << 24);
	for(;;)
	{
		GPIOD->ODR |= (1 << 12);
		//for(uint32_t i=0; i<1777777; i++);
		delay(1000);
		GPIOD->ODR &= ~(1 << 12);
		//for(uint32_t i=0; i<1777777; i++);
		delay(1000);
	}
}
